### PR TITLE
Enhancement: add jsconfig when vite-aliases run

### PR DESCRIPTION
**Pull request by tsanyqudsi**
@Subwaytime could you please review this ?

I have difficulty on the logic so i don't think it's quite efficient. However, the basic idea is :

1. Check if vite has write access to the folder.
2. If true, then check if file exists using `pathConfig` option
3. If file exists then skip this step, otherwise create the file. ( still need to find out `tsconfig.json` default config )
4. check if `paths` exists.
5. check if `paths` has the same value from `paths` generated by vite-aliases.
6. If false, merge current `paths` with the `paths` derived from vite-aliases. ( if there's no `paths` then we just create the `paths` )

### CODE REVIEW

**Comment by tsanyqudsi** [comment]
Oh please don't accept it yet.. if you like the PR, i have more questions about improving this.

**Comment by Subwaytime** [comment]
Atm i am pretty busy due to another Project and World Vue Summit.
Will check this in some days!
I am also currently working on a "rewrite" in the dev branch..
Ive got the jsconfig/tsconfig Feature almost finished but not commited, due to some issues.. so maybe your pr can help! ;)

**Comment by tsanyqudsi** [comment]
will be waiting for the "rewrite" but since the idea is quite awesome, i think i will finish the PR and help you with the "rewrite" if you want.

I also think that vite-aliases can grow into somekind of small ecosystem of plugins ? ( Is that a correct term to say ? ) For example :

1. Auto generate folder based / file based routing.
2. Content handling / file parsing based on the content of the folders.
3. etc.

Anyway, thanks for the amazing plugin. will finish the PR soon.

**Comment by Subwaytime** [comment]
Hey there! Sorry for the late response..
So overall i think it would be better to keep `vite-aliases` as it is with the current feature set, due to the ones that you mentioned already exist! Ive been working on some other Plugins, that are WIP atm, but get released soon.

The Dev branch is almost finished now, with the upcoming JSConfig/TSConfig Feature Set and a Watcher.

**Comment by tsanyqudsi** [comment]
ah ok...  waiting for it then.

**Pull request closed without merging**
